version: "3"

services:

  web:
    image: nginx:1.12-alpine
    container_name: ylab-test-webserver
    ports:
      - 8081:81
    volumes:
      - ./:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - app

  app:
    build: docker
    image: ylab-test-app:test
    container_name: ylab-test-app
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: mysql:5.7
    hostname: ylab-test-db
    container_name: ylab-test-db
    volumes:
      - /var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ylab_test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
